language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

script:
  - coverage run -m unittest testing
  
after_success:
  - coveralls